-- 创建 WEB visit log 详细表
CREATE  TABLE IF NOT EXISTS dw_db.dw_web_visit_traffic_log (
  user_id string,
  selection_city_id   string,
  client_time   string,
  user_based_city_id   string,
  referer_full_url   string,
  referer_page   string,
  referer_page_id   string,
  referer_page_name   string,
  current_full_url   string,
  current_page   string,
  current_page_id   string,
  current_page_name   string,
  channel_code   string,
  page_param   string,
  client_param   string,
  guid   string,
  client_ip   string,
  os_type   string,
  os_version   string,
  brower_type   string,
  brower_version   string,
  phone_type   string,
  server_time   string,
  referer_host  String,
  referer_query String,
  referer_ref String,
  current_host String,
  current_query String,
  current_ref String,
  current_host_city_id String
) partitioned by (p_dt string);
