-- 创建 app action log 详细表
CREATE TABLE if not exists dw_db.dw_app_action_detail_log (
     mac                string,
     dvid               string,
     model              string,
     os                 string,
     name               string,
     channel            string,
     version            string,
     uid                string,
     net                string,
     ip                 string,
     ccid               string,
     gcid               string,
     longtitude         string,
     latitude           string,
     action_id          string,
     action_name        string,
     action_cname       string,
     current_page_id    string,
     current_page_name  string,
     current_page_cname string,
     click_time         string,
     extend             string,
     bp_id              string,
     bp_name            string,
     server_time        string,
     client_ip          string
) partitioned by (p_dt string);
